### ISSUE TITLE
accountアプリの作り込み

### ISSUE THREAD

**Issue by cardene777** [cardene777/teque#37]
Boostrapを使用して見た目をよくしたり、ソーシャル認証機能をつけたりしてください。

**Comment by cardene777** [comment]
今週末までにお願いします。

**Comment by musashi-0130** [comment]
とくに進んでませんがhtmlとsccについて少し理解を深めれたので明日からまたがんばります

**Comment by cardene777** [comment]
ユーザー名と学籍番号で登録できるように。
